# SwiftLint Configuration for WebPark

# Paths to include during linting
included:
  - Sources
  - Tests

# Paths to ignore during linting
excluded:
  - .build
  - .swiftpm
  - DerivedData

# Rules to disable
disabled_rules:
  - trailing_whitespace # Sometimes useful for formatting
  - todo # TODOs are fine during development

# Rules to enable that are opt-in
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - sorted_imports
  - strict_fileprivate
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

# Identifiers
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - URL
    - res
    - sut # System Under Test (common in tests)

# Force unwrapping is allowed in tests
force_unwrapping:
  severity: error

# Custom rules
custom_rules:
  no_print:
    name: "Print statements"
    regex: "print\\("
    match_kinds: 
      - identifier
    message: "Avoid using print() in production code. Use proper logging instead."
    severity: warning
